import { SiteCopy } from '../types/siteCopy';

// Hedosoph brand locale - UI/Site copy
// Auto-generated by Brand Setup tool
const hedosophStrings: SiteCopy = {
    "home": {
      "mainTitle": "Hedosophia AI Decision Intelligence Toolkit",
      "welcomeLead": "Welcome to your centralized toolkit designed to guide Hedosophia's employees through best practices in AI-enhanced investment decision-making and operational streamlining.",
      "helpYouIntro": "This toolkit is here to help you:",
      "helpYouList": [
        "Leverage AI to enhance investment analysis and insights",
        "Streamline operations by automating repetitive tasks",
        "Develop self-sufficient AI capabilities to reduce external dependency",
        "Improve overall investment decision-making processes"
      ],
      "quickReferenceIntro": "You'll find expert guides covering every key stage of AI integration for investment and operations:",
      "quickReferenceList": [
        "Foundational AI concepts for investment professionals",
        "Workflow best practices for AI-driven decision-making",
        "Methods for advanced investment analysis with AI",
        "Strategies for operational efficiency through AI automation",
        "Building and maintaining internal AI capabilities",
        "Ethical considerations and governance in AI investments",
        "Case studies of high-profile AI-enhanced investments"
      ],
      "guidesDescription": "Each guide includes clear explanations, practical workflows, and adaptable methods you can use to optimize your decision-making processes.",
      "journeyTitle": "AI Decision Intelligence Journey",
      "journeySubtitle": "Click any stage to view relevant workflows and guides",
      "journeySteps": {
        "launch": {
          "title": "Foundation",
          "description": "Building core AI understanding and identifying key areas for enhancement in investment and operations."
        },
        "generateTestRides": {
          "title": "Exploration",
          "description": "Exploring AI tools and methodologies for specific investment analysis and operational tasks."
        },
        "inStore": {
          "title": "Implementation",
          "description": "Integrating AI solutions into daily investment workflows and operational processes."
        },
        "followUp": {
          "title": "Optimization",
          "description": "Refining AI usage for continuous improvement in decision-making and efficiency."
        },
        "welcome": {
          "title": "Mastery",
          "description": "Achieving self-sufficient AI capabilities and pioneering new applications within the firm."
        }
      }
    },
    "assets": {
      "title": "AI Decision Intelligence Resources",
      "introParagraph1": "Welcome to the central hub for all AI decision intelligence resources, including workflow templates, analytical frameworks, and interactive learning materials designed to enhance your investment capabilities.",
      "aboutContentHeading": "About the Content",
      "aboutContentP1": "You can browse and download resources by decision-making phase, content type, and AI application area.",
      "phase1LeadIn": "<strong>Foundational Phase resources (available now):</strong>",
      "phase1Details": "Includes core AI concepts relevant to investment, introductory workflows for decision support, and guides to identify automation opportunities.",
      "phase2LeadIn": "<strong>Advanced Phase resources (coming soon):</strong>",
      "phase2Details": "Comprehensive implementation guides for advanced analytical models, specialized content for due diligence and market analysis, and strategies for building proprietary AI tools will be available from Q2 2025.",
      "filterHeading": "Filter Resources by:"
    },
    "messages": {
      "title": "AI Integration Communications",
      "introParagraph1": "All messaging here is designed as a starting point for communicating AI's strategic role within Hedosophia, addressing adoption, and building enthusiasm for AI-driven initiatives across your teams.",
      "introParagraph2": "Everything is flexible, editable, and designed to be customized for your audience. Use these templates as-is or adapt the tone, language, and technical depth to suit your team's knowledge level and internal culture.",
      "filterHeading": "Filter AI Messages by:"
    },
    "guides": {
      "title": "AI Decision-Making Guides",
      "introParagraph1": "These guides provide structured workflows, best practices, and methodologies to enhance your investment decision-making processes through the strategic application of AI.",
      "introParagraph2": "Each guide offers actionable steps and insights to help you leverage AI effectively, reduce reliance on external consultants, and improve the quality and speed of your analysis.",
      "filterHeading": "Filter Decision Guides by:",
      "availableGuidesTitle": "Available Decision Guides",
      "guideContentTitle": "Guide Content",
      "selectGuideMessage": "Select a guide to view its decision-making workflow and methods."
    },
    "help": {
      "title": "Support & Guidance",
      "sections": [
        {
          "heading": "How to Use This AI Toolkit",
          "content": [
            "<strong>Start with foundational workflows:</strong> Each guide builds upon core concepts, creating a structured path to AI-enhanced decision-making.",
            "<strong>Apply immediately:</strong> Use the practical workflows and methods to begin integrating AI into your investment analysis and operational tasks right away.",
            "<strong>Foster self-sufficiency:</strong> These resources are designed to empower internal teams, reducing the need for external consultants.",
            "Whether you're developing new investment strategies, optimizing due diligence, or automating back-office functions, this toolkit helps make AI actionable and impactful for every team member."
          ]
        },
        {
          "heading": "Need Support?",
          "content": [
            "If you have questions about integrating AI into your investment processes or need guidance on developing self-sufficient AI capabilities, please reach out to the internal AI task force.",
            "We're here to support Hedosophia's AI transformation journey every step of the way — let's build a smarter, more efficient future together."
          ]
        }
      ]
    },
    "navigation": {
      "homeTab": "Home",
      "assetsTab": "Resources",
      "messagesTab": "Communications",
      "guidesTab": "Guides",
      "helpTab": "Help"
    }
  }

export default hedosophStrings;